####
# Travis configuration for codeception-drupal-runserver.
####

language: php

php:
  - 5.4
  - 5.5
  - 5.6

# This builds the environment.
install:
  - composer self-update
  - composer install

# Before running the main test script we want to ensure we've installed Drupal and set up Codeception.
before_script:
  - ./testinit.sh
  - vendor/bin/codecept build

script:
  - vendor/bin/codecept run --debug

# Whitelist branches to test.
branches:
  only:
    - master

after_failure:
  - cat tests/_output/drush.runserver.errors.txt
  - cat tests/_output/drush.runserver.output.txt
  - cat tests/_output/BasicServerTestCept.fail.html
  - vendor/bin/drush st -r testsites/drupal7/drupal-7.x